# Site settings
title: 魅图科技-专注于开发基于地图的政府、企业、商家、公众应用
email: meitukeji@163.com
description: "魅图科技-专注于开发基于地图的政府、企业、商家、公众应用"
baseurl: ""
url: "http://www.meitukeji.com"

# Build settings
markdown: kramdown
permalink: pretty
